version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - w
      - pwd
      - ls -la
      - node --version
      - npm --version
  build:
    commands:
      - echo "nothing to do."
artifacts:
  name: builtAssets
  files:
    - "**/*"
  base-directory: public
