version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - ls -la
      - cat package.json
      - npm install
  pre_build:
    commands:
      - npm run typecheck
      - npm run lint
  build:
    commands:
      - npm run build
artifacts:
  name: builtAssets
  files:
    - "**/*"
  base-directory: public
